### ISSUE TITLE
Aktuelle Abstürze

### ISSUE THREAD

**Issue by printerboi** [Jako9/Announcer_BOT#15]
Aktuell tritt immer mal wieder der Fehler auf, dass Pakete angeblich in falscher Reihenfolge bei der Datenbank ankommen. Laut diversen Quellen sollte man die max_package_size erhöhen, da die übertragenen Daten von der DB zum Bot das Limit überschreiten. Ob das die Sache final löst lässt sich jetzt aber leider noch nicht absehen.

**Comment by printerboi** [comment]
https://stackoverflow.com/questions/8062496/how-to-change-max-allowed-packet-size

**Comment by printerboi** [comment]
Wir müssen vermutlich dafür in den Container der Datenbank eine Konfigurationsdatei induzieren!

**Comment by Jako9** [comment]
Resolved
